graph TD
    EventTarget((EventTarget)) --> Node((Node))
    Node --> Document((Document))
    Node --> DocumentFragment((DocumentFragment))
    Node --> Element((Element))
    Element --> HTMLElement((HTMLElement))
    HTMLElement --> HTMLAnchorElement((HTMLAnchorElement))
    HTMLElement --> HTMLButtonElement((HTMLButtonElement))
    HTMLElement --> HTMLDivElement((HTMLDivElement))
    HTMLElement --> HTMLSpanElement((HTMLSpanElement))
    HTMLElement --> ...((...))
    Element --> SVGElement((SVGElement))
    Node --> Attr((Attr))
    Node --> CharacterData((CharacterData))
    CharacterData --> Text((Text))
    CharacterData --> Comment((Comment))
    Node --> DocumentType((DocumentType))
    Node --> ProcessingInstruction((ProcessingInstruction))
