[package]
name = "rust"
version = "0.1.0"
edition = "2021" # rust版本

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
quote = "1.0.33"
syn = "2.0.38"
clap = { version = "4.4.7", features = ["derive"] }
